//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 09.02.2025 18:23:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace DataStructure
{
    public partial class OPAttendance {

        public OPAttendance()
        {
            OnCreated();
        }

        public int ID { get; set; }

        public Status Status { get; set; }

        public TimeSpan? Late { get; set; }

        public string? Reason { get; set; }

        public int OperationID { get; set; }

        public int UserID { get; set; }

        public virtual Operation Operation { get; set; }

        public virtual User User1 { get; set; }

        public virtual Slot Slot { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
