//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 09.02.2025 18:23:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace DataStructure
{
    public partial class Slot {

        public Slot()
        {
            OnCreated();
        }

        public int ID { get; set; }

        public string Name { get; set; }

        public int Color { get; set; }

        public int SectionID { get; set; }

        public int TrainingID { get; set; }

        public virtual Section Section { get; set; }

        public virtual Training Training { get; set; }

        public virtual OPAttendance OPAttendance { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
