//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 15.02.2025 20:22:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace DataStructure
{
    public partial class Training {

        public Training()
        {
            this.Trainers = new List<Trainers>();
            this.Users = new List<User>();
            this.Slots = new List<Slot>();
            OnCreated();
        }

        public int ID { get; set; }

        public string Name { get; set; }

        public virtual IList<Trainers> Trainers { get; set; }

        public virtual IList<User> Users { get; set; }

        public virtual IList<Slot> Slots { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
